version: "3"
services:
  expense-tacker:
    container_name: expense
    build:
      dockerfile: Dockerfile
      context: ./glory-expense-tracker
    image: olakara/expense-tracker
    ports:
      - "3000:3000"
  finance:
    container_name: finance
    build:
      dockerfile: Dockerfile
      context: ./glory-finance
    image: olakara/finance
    ports:
      - "4000:4000"
  notifications:
    container_name: notifications
    build:
      dockerfile: Dockerfile
      context: ./glory-notifications
    image: olakara/notifications
    ports:
      - "5000:5000"